import Header from '@/components/Layout/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'
import { Box, Container } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Header />
          <Container sx={{ minWidth: '90vw' }}>
            <Box pt={3} pb={3}>
              {children}
            </Box>
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
